version: "1"

services:
  - type: web
    name: myapp
    runtime: node
    repo: https://github.com/ZINEBMOKHLIS/myapp
    branch: main
    buildCommand: npm install
    startCommand: npm start
    plan: free
